1.1 数据操作入门

In [2]:
import torch
a = torch.tensor([1, 2, 3])
a

tensor([1, 2, 3])

In [3]:
a.shape
sum(a)
# b = torch.arange(12).reshape(4,3)
b = torch.arange(2,14,dtype=torch.float32).reshape(2,3,2)
c = torch.arange(3,dtype=torch.float32 )
b,c
# b.shape
c.shape
b.numel()#也是查看size的
chushi = id(b)
b = b.reshape(4,-1)#-1自动计算剩余维度
b,id(b),chushi

(tensor([[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.],
         [11., 12., 13.]]),
 2819981411248,
 2819975542832)

In [4]:
torch.zeros([3,4])
torch.ones([3,4])
torch.randn([3,4])

tensor([[-0.5169, -1.4062,  1.3045, -0.9848],
        [-0.2755,  0.1513,  1.4232,  0.9793],
        [-0.1818,  0.7290, -0.4031, -0.3194]])

In [ ]:
x = torch.tensor([1.0,2,3,4],dtype = torch.float32)
exp_x = torch.exp(x)
exp_x
y = torch.tensor([0.1,0.2,0.3,0.4],dtype = torch.float32)
x == y
x.sum()
x[::2]
z = torch.arange(12).reshape(3,4)
z,z[-1][0],z[-1,0:2]#开区间
z[0,:] = 1#:代表该列所有元素
z


tensor([[ 1,  1,  1,  1],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

1.2 张量

In [ ]:
A = torch.arange(12).reshape(3,4)
B = A.clone()
A * B#按元素相乘
A_sum_col = A.sum(axis = 0)
A_sum_col.shape#会降维
A_sum_col = A.sum(axis = 1,keepdim=True)
A/A_sum_col
# A_sum_col = A.cumsum(axis = 0)#累加和函数，累加上面所有行
# A_sum_col



tensor([[0.0000, 0.0667, 0.1111, 0.1429],
        [0.3333, 0.3333, 0.3333, 0.3333],
        [0.6667, 0.6000, 0.5556, 0.5238]])

In [40]:
X = torch.tensor([[1.0,2.0],[3.0,4.0]])
Y = torch.tensor([[0.1,0.2],[0.3,0.4]])
torch.dot(X.reshape(-1),Y.reshape(-1))#点积，对应元素相乘相加
x = torch.tensor([2,1],dtype=torch.float32)
torch.mv(X,x)#矩阵与向量乘法
torch.mm(X,Y)#矩阵乘法
torch.norm(X)

tensor(5.4772)

1.3 微分

In [51]:
x = torch.tensor([1.0,2.0,3.0],dtype=torch.float32,requires_grad=True)
y = 2 * torch.dot(x,x)
y.backward()
x.grad.zero_()#梯度清零
y = x.sum()
y.backward()
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad



tensor([2., 4., 6.])

In [57]:
x = torch.tensor([5.0],dtype=torch.float32,requires_grad=True)
y = x ** 2
y.backward()
y,x.grad

(tensor([25.], grad_fn=<PowBackward0>), tensor([10.]))

1.4 概率

In [89]:
from torch.distributions import multinomial
fair_probs = torch.ones([6])/6
fair_probs
counts = multinomial.Multinomial(2,fair_probs).sample((3,))#从多项分布中采样，10次试验，每次试验有6种结果，3行10列的样本
# counts = multinomial.Multinomial(100,fair_probs).sample()
sum_counts = counts.sum(axis = 0,keepdim=True)
sum_counts/sum_counts.sum()
# counts.shape

tensor([[0.0000, 0.3333, 0.1667, 0.1667, 0.1667, 0.1667]])

In [102]:
dir(torch.distributions)
help(torch.ones)
list??

Help on built-in function ones in module torch:

ones(...)
    ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor
    
    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.
    
    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.
    
    Keyword arguments:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, us

Init signature: list(iterable=(), /)
Docstring:     
Built-in mutable sequence.

If no argument is given, the constructor creates a new empty list.
The argument must be an iterable if specified.
Type:           type
Subclasses:     _HashedSeq, StackSummary, _Threads, ConvertingList, DeferredConfigList, _ymd, _Accumulator, DeprecatedList, SList, _ImmutableLineList, ...