In [1]:
import torch
import math
import numpy as np
from torch import nn
from d2l import torch as d2l

4.1 理解过拟合欠拟合

In [2]:
max_degree = 20  # 多项式的最大阶数
n_train, n_test = 100, 100  # 训练和测试数据集大小
true_w = np.zeros(max_degree)  # 分配大量的空间
true_w[0:4] = np.array([5, 1.2, -3.4, 5.6])

features = np.random.normal(size=(n_train + n_test, 1))
np.random.shuffle(features)
poly_features = np.power(features, np.arange(max_degree).reshape(1, -1))
for i in range(max_degree):
    poly_features[:, i] /= math.gamma(i + 1)  # gamma(n)=(n-1)!
# labels的维度:(n_train+n_test,)
labels = np.dot(poly_features, true_w)
labels += np.random.normal(scale=0.1, size=labels.shape)


In [5]:
# NumPy ndarray转换为tensor
true_w, features, poly_features, labels = [torch.tensor(x, dtype=
    torch.float32) for x in [true_w, features, poly_features, labels]]

features[:3], poly_features[:3, :], labels[:2]

C:\Users\hmm\AppData\Local\Temp\ipykernel_28984\1808355960.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  true_w, features, poly_features, labels = [torch.tensor(x, dtype=


(tensor([[0.7916],
         [0.8641],
         [0.7803]]),
 tensor([[1.0000e+00, 7.9160e-01, 3.1331e-01, 8.2673e-02, 1.6361e-02, 2.5903e-03,
          3.4174e-04, 3.8646e-05, 3.8240e-06, 3.3634e-07, 2.6625e-08, 1.9160e-09,
          1.2639e-10, 7.6963e-12, 4.3517e-13, 2.2965e-14, 1.1362e-15, 5.2907e-17,
          2.3267e-18, 9.6938e-20],
         [1.0000e+00, 8.6415e-01, 3.7337e-01, 1.0755e-01, 2.3235e-02, 4.0156e-03,
          5.7835e-04, 7.1397e-05, 7.7122e-06, 7.4050e-07, 6.3990e-08, 5.0269e-09,
          3.6200e-10, 2.4063e-11, 1.4853e-12, 8.5568e-14, 4.6214e-15, 2.3492e-16,
          1.1278e-17, 5.1294e-19],
         [1.0000e+00, 7.8031e-01, 3.0444e-01, 7.9186e-02, 1.5447e-02, 2.4108e-03,
          3.1352e-04, 3.4949e-05, 3.4089e-06, 2.9556e-07, 2.3063e-08, 1.6360e-09,
          1.0638e-10, 6.3854e-12, 3.5590e-13, 1.8514e-14, 9.0293e-16, 4.1445e-17,
          1.7967e-18, 7.3787e-20]]),
 tensor([5.4749, 5.3993]))

小记:hpo可以去看，推荐设计超参数使用随机，贝叶斯可能要训练几万次几千次才会比较好。

4.2 